1 entries in records
Started running calling sequence 1
Traceback (most recent call last):
  File "C:\Users\Swathi\Downloads\Etl_New\ETL_Framework\common_utils\audit.py", line 152, in wrapper
    source_count, insert_count, update_count = function(*args, **kwargs)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Swathi\Downloads\Etl_New\ETL_Framework\clicktoch\db.py", line 24, in click_to_ch
    database_name = row.targetname
                    ^^^^^^^^^^^^^^
AttributeError: 'Pandas' object has no attribute 'targetname'

Finished d_region in 0.11 seconds
Finished running calling sequence 1 in 0.11173400000552647 seconds
