[
    {
        "type": "AttributeError",
        "args": [
            "'Pandas' object has no attribute 'targetname'"
        ],
        "tb": "Traceback (most recent call last):\n  File \"C:\\Users\\Swathi\\Downloads\\Etl_New\\ETL_Framework\\common_utils\\audit.py\", line 152, in wrapper\n    source_count, insert_count, update_count = function(*args, **kwargs)\n                                               ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Swathi\\Downloads\\Etl_New\\ETL_Framework\\clicktoch\\db.py\", line 24, in click_to_ch\n    database_name = row.targetname\n                    ^^^^^^^^^^^^^^\nAttributeError: 'Pandas' object has no attribute 'targetname'\n",
        "timestamp": "2025-03-11T07:43:21.620866+00:00",
        "src": "clicktoch.db.click_to_ch",
        "obj_type": "Dimension",
        "sourceid": "region",
        "target_file": "d_region",
        "latestbatchid": 278
    }
]